sudo: required
dist: trusty

before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended cm-super
script:
- pdflatex -interaction=nonstopmode -halt-on-error SemihOnay-CV.tex

deploy:
- provider: releases
  api_key:GITHUB_TOKEN
    secure: $
  file_glob: true
  file: "*.pdf"
  skip_cleanup: true
  on:
    repo: Semyonic/Curriculum-Vitae
    branch: master
    tags: true